### ISSUE TITLE
Doesn't work right away

### ISSUE THREAD

**Issue by pb-kh** [labi-le/hyrp-kbd-layout#1]
Really enjoyed the thing, thank you!

However, it doesn't work me right from the login. That is, it doesn't display anything until i change the layout for the first time. Is there a way to make it work?

**Comment by labi-le** [comment]
Hi, I know about this problem, it didn't bother me when I used hyperland

Maybe wm has the opportunity to get the current layout right away

You can also explicitly specify which layout will be the first, but it looks creepy

**Comment by pb-kh** [comment]
yeahh, did a bit of search, we've got `hyperctl devices` which can give info of currently used layout, but it doesn't work for me cause it returns every single device as a keyboard (even my earbuds). and each of these has its own layout... 

but maybe it's enough for getting the first layout...

**Comment by pb-kh** [comment]
soo, it works for me now :) 

---
implemented within #2

**Comment by labi-le** [comment]
thanks for idea, corrected to use ipc client

**Comment by pb-kh** [comment]
nice, didn't know they export it like that
